<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Lazy\\' => array($vendorDir . '/lazy/lazy/src'),
    'LazyTest\\' => array($vendorDir . '/lazy/lazy/tests'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'BurgerTower\\Model' => array($baseDir . '/application/models'),
    'BurgerTower\\' => array($baseDir . '/application/libs'),
);
